import { DCardProps } from "@/app/(root)/(main)/post/DCard";

export const generateFakeCardData = (): DCardProps[] => {
  const generateCommentId = (index: number) => `B${index + 1}`;
  const generateReplyId = (commentId: string, index: number) => `${commentId}-${index + 1}`;

  return [
    {
      id: 'post1',
      userId: 'a1',
      userName: 'user1',
      isAnonymous: true,
      gender: 'male',
      userImage: '/icons/',
      title: '想要「增肌」怎麼吃？',
      content: '1.正能量平衡，達到合成代謝：吃的熱量大於每日需求。\n2.阻力訓練：有效將能量資源分配給骨骼肌增長。\n 3.足夠碳水化合物攝取(至少每公斤體重3~5克碳水化合物攝取)，讓訓練品質提升(碳水化合物是阻力訓練最重要的能量來源)。\n 4.油脂占總熱量20~35%，使睪固酮濃度正常成以利增肌。\n 5.充分蛋白質攝取，攝取1.2~2.0g/Kg/day蛋白質。',
      contentImage: ['/posts/post2.jpeg'],
      like: 14,
      bookmark: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
      tags: ['增肌', '蛋白質'],
      comments: [
        {
          id: generateCommentId(0),
          userId: 'a1',
          userName: 'cyi',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'male',
          content: '蛋白質好難吃滿',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: [
            {
              id: generateReplyId('B1', 0),
              userId: 'a1',
              userName: 'cyi',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '每天都很飽',
              createdAt: new Date(),
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 1),
              userId: 'a2',
              userName: 'Rose',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'female',
              content: '小鳥胃真的好難喔 😓',
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ],
        },
        {
          id: generateCommentId(1),
          userId: 'a2',
          userName: 'Rose',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'female',
          content: '減脂該怎麼吃?',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: [
            {
              id: generateReplyId('B2', 0),
              userId: 'a1',
              userName: 'shen',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '碳水少一點, 蛋白質多一點',
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          ]
        },
      ],
    },
    {
      id: 'post2',
      userId: 'a1',
      userName: '健身研究員',
      isAnonymous: false,
      gender: 'male',
      userImage: '/icons/',
      title: '【健身新手懶人包】男女健身新手菜單這樣配',
      content: '開始健身之前，先決定自己的目標\n\n 想要穿衣服更好看而想健身減肥？\n看著螢幕上的明星，想像自己鍛鍊後也能擁有同樣的健美體態和完美曲線？',
      contentImage: [
      ],
      like: 28,
      bookmark: 28,
      createdAt: '2025-01-01',
      updatedAt: new Date(),
      tags: ['健身', '初學者'],
      comments: [
        {
          id: generateCommentId(0),
          userId: 'a1',
          userName: 'user1',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'male',
          content: '卡',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: []
        },
        {
          id: generateCommentId(1),
          userId: 'a2',
          userName: 'user2',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'male',
          content: '卡',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: []
        },
        {
          id: generateCommentId(2),
          userId: 'a3',
          userName: 'user3',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'female',
          content: '卡',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: []
        },
      ]
    },
    {
      id: 'post3',
      userId: 'a1',
      userName: '吃貨小仙女',
      isAnonymous: false,
      gender: 'female',
      userImage: '/icons/',
      title: '好喝的乳清推薦',
      content: '',
      contentImage: [
      ],
      like: 16,
      bookmark: 0,
      createdAt: '2024-12-30',
      updatedAt: new Date(),
      tags: ['蛋白質', '雞蛋'],
      comments: [
        {
          id: generateCommentId(0),
          userId: 'a1',
          userName: 'user1',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'male',
          content: '回覆內文',
          createdAt: new Date(),
          updatedAt: new Date(),
          replies: []
        }
      ]
    },
    {
      id: 'post4',
      userId: 'a1',
      userName: '健身研究員',
      isAnonymous: false,
      gender: 'male',
      userImage: '/icons/',
      title: '不靠運動也能瘦的10個方法？',
      content: '不要再陷入卡路里的迷思中！從飲食改變就能瘦得快～\n\n減脂專家教你養成易瘦體質：\n「多吃蛋、吃飯咀嚼10秒還有戒掉麵包\n\n',
      contentImage: [
        '/posts/post1.jpeg',
      ],
      like: 20,
      bookmark: 10,
      createdAt: '2024-12-25',
      updatedAt: new Date(),
      tags: ['減脂', '有氧'],
      comments: [
      ]
    },
    {
      id: 'post5',
      userId: 'a1',
      userName: '健身研究員',
      isAnonymous: false,
      gender: 'male',
      userImage: '/icons/',
      title: '什麼是肌肥大 💪 🤔',
      content: '肌肥大(Hypertrophy)，是指肌肉細胞生長，讓肌纖維尺寸增大使身體肌肉尺寸提升的過程，通常是由肌肉受到適當的壓力刺激及飲食補充蛋白質發生。肌肉的尺寸增大主要是源自肌肉纖維截面積增加所致。在其他哺乳類動物的實驗中，可能會見到在運動後肌纖維數量增加的現象。\n對人類來說，目前大部分的實驗看到似乎都只有顯示肌纖維尺寸的增加。從目前的研究證據來看，人體的肌纖維數量似乎是先天決定且固定的，在成年之後似乎不會透過訓練長出更多肌纖維。\n\n肌肥大訓練的重點\n在過去許多健身愛好者甚至專業教練都會很常提到肌肥大的三大要素： 機械張力、代謝壓力和肌纖維的微損傷。但隨著近幾年的研究更新，目前唯一似乎能單獨造成肌肥大效果的要素只有機械張力，簡單來說就是要讓肌纖維承受外在負荷。肌纖維受在外在張力刺激後，會啟動一系列的生化反應，增加肌肉內的蛋白質合成，最終達到肌纖維尺寸增長的肌肥大效果。雖然各種運動都可能有助於產生肌肥大的效果，但以肌肥大效果來看，目前就各方面的研究證據統合，透過各種重量來進行阻力訓練會是最有效也最有效率的運動。\n\n以下我根據近幾年的最新研究，整理出幾個運動科學證實，在安排阻力訓練計畫時，對肌肥大最關鍵的幾個考量點：\n1.足夠的阻力 🏋️\n2.訓練至接近力竭 💪\n3.適當的休息和恢復 😴',
      contentImage: [
      ],
      like: 32,
      bookmark: 6,
      createdAt: '2024-12-24',
      updatedAt: new Date(),
      tags: ['肌肉', '肌肥大'],
      comments: [
        {
          id: generateCommentId(0),
          userId: 'a1',
          userName: '健身新手',
          userImage: '/icons/',
          isAnonymous: false,
          gender: 'male',
          content: '有建議訓練菜單嗎?',
          createdAt: '2024-12-23',
          updatedAt: new Date(),
          replies: [
            {
              id: generateReplyId('B1', 0),
              userId: 'a1',
              userName: '健身新手A',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '卡',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 1),
              userId: 'a1',
              userName: '健身新手B',
              userImage: '/icons/',
              isAnonymous: true,
              gender: 'male',
              content: '卡一個',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 2),
              userId: 'a1',
              userName: '健身新手C',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '卡',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 3),
              userId: 'a1',
              userName: '健身新手D',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '卡',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 4),
              userId: 'a1',
              userName: '健身新手E',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '卡',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
            {
              id: generateReplyId('B1', 5),
              userId: 'a1',
              userName: '健身新手F',
              userImage: '/icons/',
              isAnonymous: false,
              gender: 'male',
              content: '卡',
              createdAt: '2024-12-25',
              updatedAt: new Date(),
            },
          ]
        },
        {
          id: generateCommentId(1),
          userId: 'a1',
          userName: 'user1',
          userImage: '/icons/',
          isAnonymous: true,
          gender: 'male',
          content: '回覆內文',
          createdAt: '2024-12-23',
          updatedAt: new Date(),
          replies: []
        },
      ]
    },
    {
      id: 'post6',
      userId: 'a1',
      userName: '健身研究員',
      isAnonymous: false,
      gender: 'male',
      userImage: '/icons/',
      title: '初學者如何開始健身？',
      content: '',
      contentImage: [
      ],
      like: 10,
      bookmark: 10,
      createdAt: '2024-12-20',
      updatedAt: new Date(),
      tags: ['健身', '初學者'],
      comments: [
      ]
    },
  ];
};